<?php

namespace Database\Seeders;

use App\Models\EwcCode;
use Illuminate\Database\Seeder;

class EwcCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        EwcCode::create([
            "code"                         => "Anyag-R4",
            "name"                         => "közelebbről nem meghatározott alkatrész (160122 -> R4)",
            "short_name"                   => "eladható alkatrész",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "naponta",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "R4 Előkezelői kód",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "R4",
            "name"                         => "közelebbről nem meghatározott alkatrész (160122 -> R4)",
            "short_name"                   => "eladható alkatrész",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "naponta",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "R4 Előkezelői kód",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130205",
            "name"                         => "ásványi alapú olaj, klórvegyületet nem tartalmazó motor, hajtómű kenőolaj",
            "short_name"                   => "fáradtolaj",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 3; HP 14",
            "chemical_name_of_parts"       => "ásványolaj alapú használt kenőolaj",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130206",
            "name"                         => "szintetikus motor, hajtómű, kenőolaj",
            "short_name"                   => "fáradtolaj",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 3; HP 14",
            "chemical_name_of_parts"       => "ásványolaj alapú használt kenőolaj",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130502",
            "name"                         => "olaj-víz szeparátorokból származó iszapok",
            "short_name"                   => "olajos iszap",
            "hazardous"                    => true,
            "physical_form"                => "7",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "ásványolaj tartalmú mosófolyadék",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130507",
            "name"                         => "olaj-víz szeparátorokból származó olajat tartalmazó víz",
            "short_name"                   => "olajos víz",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "ásványolaj tartalmú kompreszzor kondenzvíz",
            "type_of_hazard"               => "irritáló",
            "hazardous_reactions"          => "nem ismert",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130701",
            "name"                         => "tüzelőolaj és dízelolaj",
            "short_name"                   => "selejt dízel olaj",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 3; HP 14",
            "chemical_name_of_parts"       => "ásványolaj alapú dízelolaj",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130702",
            "name"                         => "benzin",
            "short_name"                   => "selejt benzin",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 3",
            "chemical_name_of_parts"       => "motorbenzin",
            "type_of_hazard"               => "robbanóképes, éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "130899",
            "name"                         => "közelebbről meg nem határozott hulladékok",
            "short_name"                   => "kompresszor kondenzátum",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "ásványiolaj tartalmú kompreszzor kondenzvíz",
            "type_of_hazard"               => "irritáló",
            "hazardous_reactions"          => "nem ismert",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "150101",
            "name"                         => "papír és karton csomagolási hulladék",
            "short_name"                   => "papir csomagolási hulladék",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "150102",
            "name"                         => "műanyag csomagolási hulladék",
            "short_name"                   => "műanyag csomagolási hulladék",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "150110",
            "name"                         => "veszélyes anyagokat maradékként tartalmazó, vagy azokkal szennyezett csomagoló anyagok",
            "short_name"                   => "hulladék csomagoló anyagok",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "maradék ásványolajjal, esetleg festékkel szennyezett csomagoló anyagok",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "150111",
            "name"                         => "veszélyes szilárd porózus mátrixot tartalmazó fémből készült csomagolási hulladék, hajtógázas palack",
            "short_name"                   => "selejt hajtógázos palackok",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "kiürült hajtógázas palackban maradt anyag",
            "type_of_hazard"               => "robbanóképes, irritáló",
            "hazardous_reactions"          => "ütésre, hőre robbanhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "150202",
            "name"                         => "veszélyes anyagokkal szennyezett abszorbensek, szűrőanyagok, törlőkendők, védő felszerelések",
            "short_name"                   => "felitatóanyagok",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "ásványolajjal szennyezett rongy, fűrészpor",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160103",
            "name"                         => "termékként tovább nem használható gumiabroncsok",
            "short_name"                   => "selet gumiabroncs",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160104",
            "name"                         => "átvett gépjármű",
            "short_name"                   => "bontásra leadott gépjármű",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "alkalmanként",
            "r_sentences"                  => "",
            "c_components"                 => "C51; C23; C18",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "üzemanyag, kenőolaj, fagyálló, akku, olajszűrők, elektronikai hulladékok, egyéb veszélyes összetevők",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat, szennyeződést okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160106",
            "name"                         => "termékként tovább nem használható járművek, amelyek nem tartalmaznak sem folyadékot, sem más veszélyes összetevőket",
            "short_name"                   => "használatból kivont gépjárművek",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822, P 0299",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160107",
            "name"                         => "olajszűrők",
            "short_name"                   => "olajszűrők",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "ásványolajjal, szintetikus olajjal szennyezett olajszűrő",
            "type_of_hazard"               => "éghető, gyúlékony",
            "hazardous_reactions"          => "tüzet okozhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160110",
            "name"                         => "robbanó tulajdonságú alkatrészek(pl. légzsákok, pirotechnikai összetevők)",
            "short_name"                   => "selejt légzsák",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 1",
            "chemical_name_of_parts"       => "gépjármű légzsákja feltöltve gázzal",
            "type_of_hazard"               => "robbanóképes",
            "hazardous_reactions"          => "ütésre robbanhat",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160112",
            "name"                         => "surlódó testek, amelyek különböznek a 160111*-től",
            "short_name"                   => "kuplungtárcsa",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160113",
            "name"                         => "fékfolyadék",
            "short_name"                   => "fékfolyadék",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "glikoléter tartalmú használt fékfolyadék",
            "type_of_hazard"               => "irritáló",
            "hazardous_reactions"          => "nem ismert",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160114",
            "name"                         => "veszélyes anyagot tartalmazó fagyálló",
            "short_name"                   => "selejt fagyálló",
            "hazardous"                    => true,
            "physical_form"                => "F",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "glikoléter tartalmú használt fékfolyadék",
            "type_of_hazard"               => "irritáló",
            "hazardous_reactions"          => "nem ismert",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160117",
            "name"                         => "vasfémek",
            "short_name"                   => "vashulladék",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160118",
            "name"                         => "nem-vas fémek",
            "short_name"                   => "nem-vas fémek",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160119",
            "name"                         => "műanyagok",
            "short_name"                   => "műanyag hulladék",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160120",
            "name"                         => "üveg",
            "short_name"                   => "üveg hulladék",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160199",
            "name"                         => "közelebbről meg nem határozott hulladék(textilia)",
            "short_name"                   => "textilia",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160213",
            "name"                         => "veszélyes anyagot tartalmazó használatból kivont berendezések",
            "short_name"                   => "elektronikai hulladék",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "selejt elektroniaki hulladék",
            "type_of_hazard"               => "nem ismert",
            "hazardous_reactions"          => "nem ismert",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160601",
            "name"                         => "ólomakkumulátorok",
            "short_name"                   => "selejt akkumulátorok",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "5",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14, HP 8",
            "chemical_name_of_parts"       => "savas elektrolit",
            "type_of_hazard"               => "maró, irritáló",
            "hazardous_reactions"          => "vízzel érintkezve kifröccsen",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160801",
            "name"                         => "arany, ezüst, rénium, ródium, palladium, iridium vagy platina tartalom",
            "short_name"                   => "selejt katalizátorok",
            "hazardous"                    => false,
            "physical_form"                => "S",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "160807",
            "name"                         => "veszélyes anyagokat tartalmazó katalizátorok",
            "short_name"                   => "selejt katalizátorok",
            "hazardous"                    => true,
            "physical_form"                => "S",
            "packaging_method"             => "1",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "",
            "h_property"                   => "HP 14",
            "chemical_name_of_parts"       => "gépkocsiban lévő katalizátor",
            "type_of_hazard"               => "nem ismert",
            "hazardous_reactions"          => "nem ismert",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "200304",
            "name"                         => "emésztőgödörből származó iszap",
            "short_name"                   => "szennyezett szennyvíz iszap",
            "hazardous"                    => false,
            "physical_form"                => "9",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);

        EwcCode::create([
            "code"                         => "200399",
            "name"                         => "emésztőgödörből származó szennyvíz",
            "short_name"                   => "szennyezett szennyvíz iszap",
            "hazardous"                    => false,
            "physical_form"                => "9",
            "packaging_method"             => "8",
            "expected_delivery_frequency"  => "hetente",
            "r_sentences"                  => "nincs",
            "h_property"                   => "",
            "chemical_name_of_parts"       => "",
            "type_of_hazard"               => "",
            "hazardous_reactions"          => "",
            "origin"                       => "autóbontás",
            "technology_identifier_number" => "T1/autóbontás",
            "teaor_codes"                  => "3822",
            "can_be_deleted"               => false,
        ]);
    }
}
